# -*- coding: utf-8 -*-
"""FaceDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Q9YKvppBBReLsaPjW-eGGH-IH4bqrLs
"""

!pip install insightface
!pip install onnxruntime-gpu

import cv2
import numpy as np
# the following works around a deprecation in numpy
np.int = int
import insightface
from insightface.app import FaceAnalysis
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

# set up network  (this only needs to be done once per session - network can be used again & again)
# (it will trigger a big download when run the first time)
app = FaceAnalysis(providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))

# run detector on this face
# loop through 1000 images
for i in range(0, 1000, 25):
    # create the image filename based on the index
    filename = f'/content/drive/MyDrive/research24/image_step_{i}.png'

    # read the image
    img = cv2.imread(filename)

    # check if the image was successfully loaded
    if img is not None:
        # exchange red and blue channels
        img = img[:, :, ::-1]

        # display the image
        plt.imshow(img)
        plt.title(f'Original Image {i}')
        plt.draw()
        plt.pause(1)

        # run the detector on it
        faces = app.get(img)
        img_with_faces = app.draw_on(img,faces)

        # display the detected faces
        plt.imshow(img_with_faces)
        plt.title(f'Detected Faces in Image {i}')
        plt.draw()
        plt.pause(1)
        plt.clf()

        # get the cropped faces from the detector & the embeddings
        crop_imgs = []

        for f in faces:
          confidence = f.det_score
          bb = [int(x) for x in f.bbox]
          #if confidence >= 0.70:
           # box_color = (0, 255, 0)
          #else:
           # box_color = (255, 0, 0)

          crop = img[bb[1]:bb[3],bb[0]:bb[2]]
          crop_imgs.append(crop)
          plt.imshow(crop)
          print(f'Face with Confidence {confidence:.4f}')
          plt.draw()
          plt.pause(1)
          plt.clf()

          print(f'Image {i} - Face Confidence: {confidence}')
    else:
        print(f"Image {filename} not found.")

